### ISSUE TITLE
Create SRflowdiagram PRISMA 2020 preprint

### ISSUE THREAD

**Issue by paveljee** [drzhelnov/SRflowdiagram#1]
* Will use the following flow diagram from the [PRISMA 2020 Statement preprint](https://osf.io/preprints/metaarxiv/v7gm2/).
* The original SRflowdiagram R HTML template is somewhat messy and it does break under this complex flow diagram layout.
* Already tried using [Mermaid](https://mermaid-js.github.io/mermaid/), [Graphviz](https://graphviz.org), [flowchart.js](https://flowchart.js.org), and [DiagrammeR](http://rich-iannone.github.io/DiagrammeR/) both in R HTML and R Markdown, but none successfully as either no support for variable substitution (couldn’t integrate with R data) or difficult to create a similarly-looking diagram.
* Will likely have to use/update the original R HTML template or write from scratch.
* Can also have a look at other diagram toolkits, I used a [diagram markup list supported by the Markdown Preview Enhanced VS Code Extension](https://shd101wyy.github.io/markdown-preview-enhanced/#/diagrams).

![PRISMA 2020 flow diagram template for systematic reviews](https://raw.githubusercontent.com/drzhelnov/SRflowdiagram/main/SystematicReviewsPRISMA2020/PRISMA_2020_flow_diagram_template_for_systematic_reviews.png)

**Comment by nealhaddaway** [comment]
Would be a shame to write this from scratch, mate.. lol

**Comment by paveljee** [comment]
> Would be a shame to write this from scratch, mate.. lol

Well, actually, I’m using your template eventually! 😃 At least for the first version, I guess. It turned out to be the most appropriate.

Did you try diagram toolkits?

**Comment by nealhaddaway** [comment]
I literally wrote this yesterday, so would be nice to either let me finish what I was doing, or perhaps collaborate rather than work independently...

**Comment by paveljee** [comment]
No need anymore: https://twitter.com/nealhaddaway/status/1323997462080688129

**Comment by nealhaddaway** [comment]
Yup - managed to throw this together in a few hours this morning, so didn't think it was worth a message :) DiagrammeR is cool, but GraphViz is a PAIN...

**Comment by paveljee** [comment]
> GraphViz is a PAIN

To say the least…

**Comment by paveljee** [comment]
https://github.com/nealhaddaway/SRflowdiagram
